---
name: Dynamic Application Security Testing (DAST)
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

permissions:
  actions: read
  contents: read
  security-events: write

env:
  IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/tech-hive-store:latest
  APP_PORT: 8080
  HEALTH_ENDPOINT: http://localhost:${{ env.APP_PORT }}/actuator/health


jobs:
  dast-scan:
    name: DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Start Application Container
        run: |
          docker run -d -p ${{ env.APP_PORT }}:${{ env.APP_PORT }} --name tech-hive-store \
          ${{ secrets.DOCKERHUB_USERNAME }}/tech-hive-store:latest
          sleep 5  # Give it time to initialize
          docker logs tech-hive-store  # Check logs for errors

      - name: Check running containers
        run: docker ps -a

      - name: Wait for container to Become Healthy
        run: |
          echo "Checking application health endpoint: ${{ env.HEALTH_ENDPOINT }}"
          for i in {1..60}; do
            STATUS=$(curl -s -o /dev/null -w '%{http_code}' ${{ env.HEALTH_ENDPOINT }})
            echo "Attempt $i: HTTP Status: $STATUS"
            if [ "$STATUS" == "200" ]; then
              echo "✅ Application is up!"
              curl -s ${{ env.HEALTH_ENDPOINT }}
              exit 0
            fi
            sleep 10
          done
          echo "❌ Application did not start or health endpoint unavailable!" && exit 1

      - name: Run ZAP OWASP full scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:${{ env.APP_PORT }}'
          cmd_options: '-a -j -l WARN -z "-addoninstallall" '
          allow_issue_writing: true

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: DAST_Report.html
          path: owasp-zap-report.html

      - name: Stop and Cleanup Docker
        if: always()
        run: |
          echo "Stopping and removing application container..."
          if docker ps -a --format '{{.Names}}' | grep -q "tech-hive-store"; then
            docker stop tech-hive-store && docker rm tech-hive-store
          fi
          echo "Pruning unused containers and images..."
          docker container prune --force
          docker image prune --force