name: Discord Notification

permissions:
  contents: read
  actions: read

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      title:
        required: true
        type: string
      description:
        required: true
        type: string
      color:
        required: false
        type: string
        default: '7506394' # Blue
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification with Embed
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$(jq -n \
          --arg username "GitHub Actions" \
          --arg title "${{ inputs.title }}" \
          --arg description "${{ inputs.description }}" \
          --arg color "${{ inputs.color }}" \
          --arg repo "${{ github.repository }}" \
          --arg timestamp "$(date --utc +%Y-%m-%dT%H:%M:%SZ)" \
          '{
              username: $username,
              embeds: [{
                title: $title,
                description: $description,
                color: ($color | tonumber),
                footer: { text: "Repository: \($repo)" },
                timestamp: $timestamp
              }]
            }'
          )" \
          ${{ secrets.DISCORD_WEBHOOK }}