name: Discord Notification

permissions:
  contents: read
  pull-requests: read
  actions: read

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      title:
        required: true
        type: string
      description:
        required: true
        type: string
      color:
        required: false
        type: string
        default: '7506394' # Blue
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      DISCORD_TITLE: ${{ inputs.title }}
      DISCORD_DESCRIPTION: ${{ inputs.description }}
      DISCORD_COLOR: ${{ inputs.color }}
    steps:
      - name: Send Discord Notification with Embed
        run: |
          jq -n \
            --arg username "GitHub Actions" \
            --arg title "$DISCORD_TITLE" \
            --arg description "$DISCORD_DESCRIPTION" \
            --arg color "$DISCORD_COLOR" \
            --arg repo "${{ github.repository }}" \
            --arg timestamp "$(date --utc +%Y-%m-%dT%H:%M:%SZ)" \
            '{
              username: $username,
              embeds: [{
                title: $title,
                description: $description,
                color: ($color | tonumber),
                footer: { text: "Repository: \($repo)" },
                timestamp: $timestamp
              }]
            }' | curl -H "Content-Type: application/json" -X POST -d @- "$DISCORD_WEBHOOK"