name: Docker Build & Push

on:
  workflow_call:
    inputs:
      project_name:
        description: "Name of the project"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME: { required: true }
      DOCKERHUB_PASSWORD: { required: true }

permissions:
  contents: read # needed to checkout code
  packages: write # needed for pushing Docker images to GHCR or registry

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate analysis

      - name: Download Maven Target
        uses: actions/download-artifact@v4
        with:
          name: maven-target

      - name: Run Docker build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:latest
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:latest

      - id: meta
        run: echo "tags=ghcr.io/${{ github.repository }}/${{ inputs.project_name }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"
