---
name: Code Analysis

permissions:
  contents: read
  actions: read


on:
  workflow_call:
    inputs:
      cache-key:
        description: 'Sonar cache key'
        required: true
        type: string
      project_key:
        description: 'SonarQube project key'
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      GH_PAT:
        required: true
      JASYPT_ENCRYPTOR_PASSWORD:
        required: true

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Month
        shell: bash
        run: |
          echo "MONTH=$(date +'%m')" >> "$GITHUB_ENV"

      - name: Cache SonarQube
        id: cache-sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ inputs.cache-key }}

      - name: Code Analysis with SonarQube
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
          GH_PAT: ${{ secrets.GH_PAT }}
          JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage, test -Dsonar.projectKey=${{ inputs.project_key }} -Dsonar.host.url=https://sonarcloud.io
