name: Setup Workflow

permissions:
  contents: read
  issues: read


on:
  workflow_call:
    outputs:
      cache-key:
        description: "The cache key for Maven dependencies"
        value: ${{ jobs.setup.outputs.cache-key }}  # Explicitly define the output

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.generate-cache-key.outputs.cache_key }}  # Store cache key manually
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'  # Cache Maven dependencies

      - name: Generate Cache Key
        id: generate-cache-key
        run: echo "cache_key=maven-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}" >> "$GITHUB_ENV"  # Generate cache key

      - name: Debug Generated Cache Key
        run: |
          echo "Generated Cache Key: ${{ steps.generate-cache-key.outputs.cache_key }}"


      - name: Cache Maven dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ env.cache_key }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Install Dependencies
        run: mvn -B dependency:resolve dependency:resolve-plugins